language: ruby
branches:
  only:
    - master
install: bundle
env:
  global:
    - secure: "VVyIT+ENYyB9M/9LGDt1h6HJ8zdBvFYuP1Ck5+ikmxyu4Y+ghycH35TjeSKZHntO65FN5yGC2mWjZT0we7JH2Vis3crlFklZUHQIzVZuAnAFXElpZsnYMxKXvmY/aL7QleA9inivruiLB9u3j/vWAuZ7q0RCBwemv6YTh6ah8Kw="
script: jgd -u https://yegor256:$PASSWORD@github.com/tpc2/tpc2.com.git

